### ISSUE TITLE
🚨  DO NOT LEAK YOUR UNSPLASH API KEYS  🚨

### ISSUE THREAD

**Issue by tiagorangel2011** [kommitters/editorjs-inline-image#120]

**Comment by tiagorangel2011** [comment]
this is dead

**Comment by miguelnietoa** [comment]
Hi @tiagorangel2011, 

Thank you for raising this issue. We've just released [v2.0.0](https://github.com/kommitters/editorjs-inline-image/releases/tag/v2.0.0), which addresses the need for setting a proxy URL.

With this release, the Unsplash access key can now be securely set in the backend of the proxy API. This ensures that the plugin operates without exposing any access tokens on the client-side.

To implement this change, please refer to our guide on setting up the proxy for the Unsplash API: [Proxy for Unsplash API](https://github.com/kommitters/editorjs-inline-image/blob/main/proxy_api.md).

Thanks again for bringing this to our attention!
