### ISSUE TITLE
spesific request image size

### ISSUE THREAD

**Issue by oendnsk675** [kommitters/editorjs-inline-image#135]
### Is your feature request related to a problem? Please describe.

How to query a specific image size? Because if I take all the images from Unsplash, some of the images are very tall, I want certain images to be Landscape size.

**Comment by MarioRodriguezS** [comment]
@oendnsk675 Thanks a lot for reporting the issue, it was implemented and is available in v2.1.0. Please let us know if it is helpful for you. Cheers
