### ISSUE TITLE
Please add typescript support

### ISSUE THREAD

**Issue by hasnath1** [kommitters/editorjs-inline-image#37]
**I am working on a big project so I need typescript support . I tried to rewrite the library to typescript but failed . Please write this library in typescript . If you need help , I will also help . Please bro , rewrite this library in typescript .**

**Comment by juanhurtado10** [comment]
Hi @hasnath1!!! thanks for reaching out!!

Unfortunately, rewriting this library in Typescript is not part of our Roadmap.  

Good luck with your endeavors!!
