### ISSUE TITLE
Add tab for file upload

### ISSUE THREAD

**Issue by tiotdev** [kommitters/editorjs-inline-image#8]
I am currently using both https://github.com/editor-js/image and this tool since I want to offer both upload from file and Unsplash search.
I would prefer to have image upload from file like in editorjs-image available as first tab in this tool.

**Comment by moazam1** [comment]
+1

**Comment by taurenshaman** [comment]
I created a [hard fork](https://github.com/tunaltd/blocks-editor/tree/main/src/components/one-image), which adds image upload based on [flow.js](https://github.com/flowjs/flow.js) and search on current server.
* Default: search on (current deployed) server. (need more test)
* Unsplash
* Upload (works well)
* Embed URL

![image](https://user-images.githubusercontent.com/1308706/106742534-1d51fe00-6658-11eb-92b4-8410ed6a56b6.png)

![image](https://user-images.githubusercontent.com/1308706/106742567-280c9300-6658-11eb-84b7-cd6b2a0f9603.png)

**Comment by moazam1** [comment]
@taurenshaman brilliant. Can you add an option to hide tab(s)?

**Comment by taurenshaman** [comment]
> @taurenshaman brilliant. Can you add an option to hide tab(s)?

I made some break changes to the code, so you can follow these 2 steps:
1. add a property like `supportEmbedUrl` to the config:
```
const editor = EditorJS({
  tools: {
      image: {
        class: InlineImage,
        inlineToolbar: true,
        config: {
          unsplash: {
            appName: 'your_app_name',
            clientId: 'your_client_id'
          },
          supportEmbedUrl: true
        }
      }
  }
});
```
2. update the `render()` function in controlPanel.js:
```
// 2.1 tab
if(this.config.supportEmbedUrl)
      tabWrapper.appendChild(embedUrlTab);
// 2.2 panel
if(this.config.supportEmbedUrl)
      wrapper.appendChild(embedUrlPanel);
```

**Comment by juanhurtado10** [comment]
Hey @tiotdev !! Thanks for reaching out. I've looked at your fork and looks great!. By now, this plugin is intended to be used just with inline images not uploaded ones. Best!!
