### ISSUE TITLE
Image zoom when clicked

### ISSUE THREAD

**Issue by samandar-boymurodov** [kommitters/editorjs-inline-image#90]
### Is your feature request related to a problem? Please describe.
Could you please add an ability to zoom in the image when clicked?

That would be great if image can be scaled up when user clicks it during read mode.

![image](https://user-images.githubusercontent.com/65066111/191536749-f660ae3a-0b6d-4149-b2d8-8f8f65f88e4d.png)

**Comment by varun7singh** [comment]
can i work on this?

**Comment by miguelnietoa** [comment]
> can i work on this?

Of course, go for it! @varun7singh 🚀

**Comment by miguelnietoa** [comment]
This feature was implemented in #97 and is already available in the version `1.2.0` 🎉

**Comment by samandar-boymurodov** [comment]
Thank you for the update!
