### ISSUE TITLE
Provide image select callback

### ISSUE THREAD

**Issue by Juratbek** [kommitters/editorjs-inline-image#96]
### Is your feature request related to a problem? Please describe.

I am trying to change selected image url. The url has some parameters, I have to add 'q' parameter in order to change image quality or fetch compressed image from unsplash

https://unsplash.com/blog/the-5-minute-guide-to-image-quality/

### Describe the solution you'd like

I need a callback receiving selected image data and returning changed block data, which will be given to the editor for rendering. In other words, we can add callback, which will be called after image select action and before giving the block data to the editor
<img width="570" alt="Screenshot 2022-11-19 at 17 29 25" src="https://user-images.githubusercontent.com/55176773/202850878-7ed38c48-7a04-410b-8dd2-244e4ca9df6a.png">

**Comment by JoseZapata3** [comment]
Hello @Juratbek ,

Thank you for your interest in our libraries. We are preparing to begin work on your request but would like to confirm our understanding of it:

You are proposing to add an additional property to the plugin configuration. This property would allow users to specify a function that modifies the behavior of images selected from Unsplash. The goal is to apply certain enhancements to these images before they are rendered, ensuring they display with the desired modifications. Is this correct?

**Comment by JoseZapata3** [comment]
Hi @Juratbek ,

We are pleased to inform you that we have implemented support for the feature you requested. Now, you can specify quality and dimension parameters directly in the configuration. We look forward to any comments or feedback you might have. This enhancement will be included in our next release (v2.2.0).

Best regards.
